app_name: Application Name

twitter:
  consumer_key: set me in config.private.yml
  consumer_secret: set me in config.private.yml
  oauth_token: set me in config.private.yml
  oauth_token_secret: set me in config.private.yml
